name: "Update metadata"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  metadata-updater:
    name: Update the metadata
    runs-on: ubuntu-latest
    # permissions: read-all|write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Update metadata
        run: npm run update-metadata

      - name: Commit Changes
        run: |
          git config user.name 'vighnesh153'
          git config user.email 'me@vighnesh153.com'
          git add metadata
          git commit -m "chore: update metadata" --no-verify

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit-message: "chore: update metadata"
          committer: "GitHub <noreply@bot.actions.github.com>"
          author: "GitHub <noreply@bot.actions.github.com>"
          branch: update-metadata
          delete-branch: true
          title: '[Github Actions Bot] Update metadata'
          body: |
            Update metadata
            - Updated total words count
            - Updated list of all words
          labels: |
            automated
          assignees: vighnesh153
          reviewers: vighnesh153
          draft: false
